name: Build and test

on:
  push:
    branches: [ "main, develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      
      - name: Configure and build
        run: |
          cmake -B bin .
          cmake --build bin --config Release
      
      - name: Run tests
        run: |
          cd bin
          ctest
          cd ..
