name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      
      - name: Configure and build
        run: |
          cmake -B bin .
          cmake --build bin --config Release
      
      - name: Run tests
        run: |
          cd bin
          ctest
          cd ..

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number  }}
          release_name: Release ${{ github.run_number  }}
          body: |
            Automatic release for the version ${{ github.run_number }}
          prerelease: true
      
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: gradient-descent-ubuntu-latest
          asset_path: ./bin/gradient_descent
          asset_content_type: application/octet-stream
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradient-descent:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/gradient-descent:latest
